config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :ideas do
    resources :comments do

    end
  end
  root "ideas#index"
end

app/models/ability.rb
class Ability
	include CanCan::Ability

	def initialize(user)

		user ||= User.new
		
		can [:edit, :update, :destroy], Idea do |idea|
			user == idea.user
		end

		can :destroy, Comment do |comment|
			user == comment.user
		end

		can :flag, Comment do |comment|
			user == comment.user
		end
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idea
	belongs_to :user

end

app/models/idea.rb
class Idea < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ideas
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, except: [:create]


	def create

		@idea = Idea.find(params[:idea_id])
		@comment = @idea.comments.new(params[:comment].permit(:name, :body))
		@comment.user = current_user

		if current_user
			if @comment.save
				redirect_to idea_path(@idea)
			else
				render 'ideas/show'
			end
		else
			redirect_to new_user_session_path
		end
	end

	def destroy
		@idea = Idea.find(params[:idea_id])
		@comment = @idea.comments.find(params[:id])
		@comment.destroy
		redirect_to idea_path(@idea)
	end

	def update
		@idea = Idea.find params[:idea_id]
		@comment = Comment.find params[:id]
		if can? :flag, @comment
			if @comment.is_flagged
				@comment.is_flagged = false
			else
				@comment.is_flagged = true
			end
			@comment.save
			redirect_to @idea
		else
			redirect_to @idea, alert: "You can not flag this... "
		end
	end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @idea = Idea.new
    @ideas = Idea.all.order('created_at DESC')
  end

  def new
		@idea = Idea.new
    @ideas = current_user.ideas.build
  end

  def create
    # @idea = Idea.new(idea_params)
    @idea = current_user.ideas.build(idea_params)
     if @idea.save
    redirect_to @idea
  else
    render 'new'
  end
end

  def show
    @idea = Idea.find(params[:id])
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update (params[:idea].permit(:title, :body))
      redirect_to @idea
    else
      render 'edit'
  end
end

def destroy
  @idea = Idea.find(params[:id])
  @idea.destroy

  redirect_to ideas_path

end
  private

  def idea_params
    params.require(:idea).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/comments/_comment.html.erb
<div class="comments">

<div class="comment_content">
  <p class ="comment-name"><strong> <%= comment.name %></strong></p>
  <p class = "comment.body"><%= comment.body %></p>
  <p class = "comment.time" style="text-decoration: underline">👆🏼 was commented <%= time_ago_in_words(comment.created_at) %> ago</p>
</div>

<% if comment.idea.user == current_user %>

<p><%= link_to 'Delete', [comment.idea, comment ],
        method: :delete,
        class: "button",
        data: {confirm: "Are you sure?"}%></p>
        <%end %>

</div>

app/views/comments/_form.html.erb
<%= form_for ([@idea, @idea.comments.build]) do |f| %>

<div class="form-group">
  <%= f.label :name , :style =>"color:white;"%>
  <%= f.text_field :name, class: 'form-control', :style =>"width:60%;" %>
</div>


<div class="form-group">
  <%= f.label :comment, :style =>"color:white;" %>
  <%= f.text_area :body, class: 'form-control' , :style =>"width:60%;"%>
</div>

<%= f.submit class: 'btn btn-primary' %>

<% end %>

app/views/ideas/_form.html.erb
<div id="errors">
<% @idea.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</div>

<%= form_for @idea do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :body %><br>
  <%= f.text_area :body %>
</p>

<p><%= f.submit  %></p>

<% end %>

app/views/ideas/edit.html.erb
<div id="page_wrapper">
<h1>Edit Idea</h1>
<%= render 'form' %>
</div>

app/views/ideas/index.html.erb
<h1>
  <canvas id="myCanvas" style="margin-left:-4%; margin-top:-11%;"></canvas>
  <script type="text/javascript" src="https://s3.amazonaws.com/codecademy-content/courses/hour-of-code/js/bubbles.js"></script>
  <script type="text/javascript" src="main.js"></script>
  <script>

  var myName = "Great Ideas"
  var letterColors = white;
  bubbleShape = "square";

  drawName(myName, letterColors);
  bounceBubbles()</script>
</h1>

<% @ideas.each  do |idea| %>
<div class="idea-wrapper" style="margin-left:4%;">
  <div class="row" >
    <div class="col-md-6" ><h2 class = "title" ><%= link_to idea.title, idea %></h2></div>
    <div class="col-md-6"><h2 ><%= link_to "Reviews", idea_path(idea), class: 'btn btn-primary btn-xs '%></h4></div>
    </div>
    <p class = "date" style="color:white;"><%= idea.created_at.strftime("%B, %d, %Y") %></p>
    <p class = "body" style="color:white;">
      <%= idea.body %>
    </p>
    <h1>∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙</h1>
  </div>
  <% end %>

app/views/ideas/new.html.erb
<h1>New ideas</h1>

<div id="errors">
<% @idea.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</div>

<%= form_for :idea, url: ideas_path do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :body %><br>
  <%= f.text_area :body %>
</p>

<p><%= f.submit  %></p>

<% end %>

app/views/ideas/show.html.erb
<div style="margin-left:4%;">

<h1 class="title" style="color:white;">
  <%= @idea.title %>
</h1>

<p class="date" style="color:white;">
  Submitted <%= time_ago_in_words(@idea.created_at) %> ago
  <% if @idea.user == current_user %>
  | <%=  link_to 'Edit', edit_idea_path(@idea)  %>
  <%= link_to 'Delete', idea_path(@idea),
  method: :delete,
  data: { confirm: 'Are you sure?' } %>
  <% end %>

</p>
<p class = "body" style="color:white;">
  <%= @idea.body %>
</p>

<div id="comments" style="color:white;">
  <h2><%= @idea.comments.count %> Reviews</h2>
    <% @idea.comments.each do |comment| %>
    <%= comment.body %>
    <% if comment.is_flagged %>
  <span><i class="fa fa-flag" aria-hidden="true"></i></span>
    <% end %>

    <% if can? :destroy, comment %>
    <%= link_to 'Delete', [@idea, comment],
    method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger pull-right" %>
    <% end %>

    <% if can? :flag, comment %>
    <%= link_to (comment.is_flagged ? 'Unflag' : 'Flag'), [@idea, comment],
    method: :put, class: "btn btn-info pull-right flag-button" %>
    <% end %>
<h1>∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙</h1>
  <% end %>
  <h3>Review</h3>
    <%= render "comments/form" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FactoryIdeas</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script type="text/javascript" src="https://s3.amazonaws.com/codecademy-content/courses/hour-of-code/js/alphabet.js"></script>
</head>


<body style="background-image: url(/assets/background4.jpg); background-repeat: no-repeat;background-color:#161616;" >
  <div class="container" style="margin-top:5%;">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul id="navbar" class='nav navbar-nav'>
            <li >
              <%= link_to 'Home', '/' %></li>
            <li >
              <%= link_to 'Sign In', new_user_session_path %></li>
              <li >
                <%= link_to 'Sign Up', new_user_registration_path %></li>
                <li >
                  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete%></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <div class="btn-group" style="margin-left:-30%;">
                    <% unless @idea.nil? %>
                    <button type="button" class="btn btn-primary navbar-btn" data-toggle="modal" data-target="#newIdeaModal">
                      New Idea
                    </button>
                    <% end %>
                  </div>
                </ul>
              </div>
            </nav>

          </div>

<% unless @idea.nil? %>
<!-- Modal -->
<div class="modal fade" id="newIdeaModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New ideas</h4>
      </div>
      <div class="modal-body">

        <div id="errors">
        <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </div>

        <%= form_for :idea, url: ideas_path do |f| %>
        <p>
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </p>

        <p>
          <%= f.label :body %><br>
          <%= f.text_area :body %>
        </p>

        <p><%= f.submit  %></p>

        <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<% end %>

<!-- Latest compiled and minified JavaScript -->

          <%= yield %>
        </body>

        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end %>


        </html>